### ISSUE TITLE
User-defined separator?

### ISSUE THREAD

**Issue by Kwlio** [brettz9/append-to-clipboard#1]
Firstly, thanks for the great add-on!

Would you consider adding an option to allow the user to define their own separator(s)? It would be great if it was possible to add multiple user-defined separators for different capturing requirements (e.g. comma/csv, pipe, space, etc.) and select these from a cascading context menu.

**Comment by brettz9** [comment]
Thanks for your great suggestion!  I have a number of other to-dos on my plate now (and with little energy to do them), but I've added it as a to-do in hopes I may get to it when I have some time--no promises, but I'm hopeful. (Tech. note: A pity Firefox's SDK doesn't provide multiple-select for simple-prefs...)

**Comment by Kwlio** [comment]
Excellent, thanks for considering it!

The lack of a multiple-select option is definitely a pain. I'd be surprised if there aren't a number of Firefox users who need / want to copy several pieces of information from a page without having to paste each one in between.

As a 'bonus' suggestion, it would also be useful to be able to append link targets to the clipboard, as well as selected text; not sure if such a thing would be accessible to an add-on, though.

**Comment by brettz9** [comment]
By "link targets", I assume you mean the link URL location rather than the target attribute which indicates whether a link should open in a new window, a specific window, etc.

Yeah, that could be nice (as well as link text, in the spirit of my Copy Link Text add-on!), and yes, link locations are accessible to add-ons. Pretty much anything is accessible to a Firefox add-on which makes Firefox add-on development so fun.

**Comment by brettz9** [comment]
I've added the copying of link text or location to my to-dos list as well...

**Comment by brettz9** [comment]
Sorry I didn't get to this feature in my latest release, but as mentioned it is on the to-dos in case I might get to it... At least the extension is now working again in Firefox and now that it is now a WebExtension, also in Chrome (and possibly usable on other browsers I haven't tested like Edge).
