### ISSUE TITLE
Not working since update to 2.3.1

### ISSUE THREAD

**Issue by pulbitz** [brettz9/append-to-clipboard#16]
Not working since update to 2.3.1 in firefox.

"Extensions permissions needed" notification on the extensions button.

**Comment by brettz9** [comment]
In anticipation of changes in both Chrome and Firefox, I've updated the extension to use the up-and-coming manifest version 3. Unfortunately for append-to-clipboard users, in this new version, it has changed to become necessary for the add-on to request "scripting" permissions.

If you accept the permissions through the extensions button and still have trouble using the add-on, please let me know.

Thanks for the report! Closing, but please feel free to comment further with your experience either way.

**Comment by pulbitz** [comment]
Thanks for the detailed explanation.
But it doesn't work even though I clicked to accept the permission, the context menu doesn't come up.
I tested it on firefox 111.0.1, 112.0rc versions.

**Comment by brettz9** [comment]
Oh, good to know, thanks. I think I've found the bug. It seems to be working for me now. Let me know if 2.3.2 does it for you. Thanks!

**Comment by brettz9** [comment]
I've reverted to Manifest v2, as it seemed to work but inconsistently. The latest version from Mozilla should work now hopefully.

**Comment by pulbitz** [comment]
I kept testing on other sites, not AMO. And while testing 2.3.2, I noticed something strange.
I removed, added, and reset extensions several times, and at one point (only once) the context menu would come up. Other than that moment, it didn't work.

Anyway, 2.3.4 (Manifest v2) is working fine. Thanks!

**Comment by brettz9** [comment]
Glad to hear it, and thanks again for the report!
