### ISSUE TITLE
UPdate for the new firefox

### ISSUE THREAD

**Issue by nickherea** [brettz9/append-to-clipboard#2]
please

**Comment by brettz9** [comment]
This has now been added to `master` and has already been published at [AMO](https://addons.mozilla.org/en-US/firefox/addon/append-to-clipboard/) and also the [Chrome Web Store](https://chrome.google.com/webstore/detail/append-to-clipboard/dbpammihbikenddkkiggbdnakdoldobo?hl=en-US). Best wishes...
