### ISSUE TITLE
Will not append links on this site

### ISSUE THREAD

**Issue by nickhere1** [brettz9/append-to-clipboard#4]
https://leitesculinaria.com/category/giveaways
all i want to do is copy link by link
 selected text and  just append the links to the clipboard not the data

**Comment by brettz9** [comment]
I've implemented link appending functionality. If you opt to copy the link text, it will only copy the link text. If you do a regular copy (which doesn't mention "link text"), it will copy the URL, or, for formatted copying (e.g., if you are pasting into say an HTML email), it will copy the URL and link text. In the future, I might add some code to let you insist on only copying the URL even for formatted HTML, but currently that is a limitation. But I will close, as it seems this might meet your needs. Feel free to comment further.
